#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the getWays function below.
def getWays(n, c):
    while len(c)!=0:
        y=min(c)
        c.remove(y)
        for z in range(len(l)):
            if z>=y:
                l[z]+=l[z-y]
    return l[n]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])
    
    c = list(map(int, input().rstrip().split()))
    # Print the number of ways of making change for 'n' units using coins having the values given by 'c'
    l=[0]*(n+1)
    l[0]=1
    ways = getWays(n, c)
    fptr.write(str(ways))
    fptr.close()
